[package]
name = "image_converter_service"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
base64 = "0.22.1"
dotenv = "0.15.0"
image = "0.25.5"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.137"
tokio = "1.43.0"
